server:
  port: 8080
spring:
  application:
    name: whatsapp-reader
whatsapp:
  webhook:
    verify-token: ${WHATSAPP_VERIFY_TOKEN:cKSK-MESSAGE-APP_2027}
    app-secret: ${WHATSAPP_APP_SECRET:057bea35bc32f7418735a63b2a37f91e}
management:
  endpoints:
    web:
      exposure:
        include: health,info
