server:
  port: 8080
spring:
  application:
    name: whatsapp-reader
whatsapp:
  webhook:
    verify-token: ${WHATSAPP_VERIFY_TOKEN:KSKReadingService_2027}
    app-secret: ${WHATSAPP_APP_SECRET:636fe3003d8983e209041a89ff023459}
management:
  endpoints:
    web:
      exposure:
        include: health,info
